sudo: required
env:
services:
- docker
before_install:
- "./.travis/main.sh"
script:
- make build
- make test
deploy:
  provider: script
  script: bash -c make tp
  on:
    tags: true
    branch: master
