name: docker-metanorma

on:
  push:
    tags:
    - '*'
  pull_request:
    branches:
    - '**'
  repository_dispatch:
  workflow_dispatch:

jobs:
  build-debian:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
    - uses: actions/checkout@v2

    - name: Prepare Docker Environment
      shell: bash
      run: |
        echo '{"cgroup-parent": "/actions_job", "experimental": true, "features": { "buildkit": true }}' | sudo tee /etc/docker/daemon.json 2>/dev/null
        sudo service docker restart

    - uses: metanorma/metanorma-build-scripts/gh-rubygems-setup-action@master
      with:
        token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}

    - name: Build container
      id: build
      run: |
        make build-metanorma
        echo "::set-output name=container_name::$(make print-local-name-metanorma)"

    - uses: yuichielectric/dive-action@0.0.4
      with:
        image: ${{ steps.build.outputs.container_name }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run tests
      env:
        GITHUB_CREDENTIALS: "metanorma-ci:${{ secrets.METANORMA_CI_PAT_TOKEN }}"
      run: |
        make test-metanorma

    - name: Tag and push container
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        DOCKER_LOGIN_USERNAME: ${{ secrets.DOCKER_LOGIN_USERNAME }}
        DOCKER_LOGIN_PASSWORD: ${{ secrets.DOCKER_LOGIN_PASSWORD }}
      run: |
        make tp-metanorma latest-tp-metanorma

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Prepare Docker Environment
      shell: bash
      run: |
        echo '{"cgroup-parent": "/actions_job", "experimental": true, "features": { "buildkit": true }}' | sudo tee /etc/docker/daemon.json 2>/dev/null
        sudo service docker restart

    - uses: metanorma/metanorma-build-scripts/gh-rubygems-setup-action@master
      with:
        token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}

    - name: Build container
      id: build
      run: |
        make build-metanorma-ubuntu
        echo "::set-output name=container_name::$(make print-local-name-metanorma-ubuntu)"

    - uses: yuichielectric/dive-action@0.0.4
      with:
        image: ${{ steps.build.outputs.container_name }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run tests
      env:
        GITHUB_CREDENTIALS: "metanorma-ci:${{ secrets.METANORMA_CI_PAT_TOKEN }}"
      run: |
        make test-metanorma-ubuntu

    - name: Tag and push container latest
      if: github.ref == 'refs/heads/master'
      env:
        DOCKER_LOGIN_USERNAME: ${{ secrets.DOCKER_LOGIN_USERNAME }}
        DOCKER_LOGIN_PASSWORD: ${{ secrets.DOCKER_LOGIN_PASSWORD }}
      run: |
        make tag-metanorma-ubuntu latest-tp-metanorma-ubuntu
        
    - name: Tag and push container versioned 
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        DOCKER_LOGIN_USERNAME: ${{ secrets.DOCKER_LOGIN_USERNAME }}
        DOCKER_LOGIN_PASSWORD: ${{ secrets.DOCKER_LOGIN_PASSWORD }}
      run: |
        make tp-metanorma-ubuntu
